services:
  api:
    build:
      context: server
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - "./server:/app"  # Mount the current directory to /app in the container
    networks:
      - reservation-api
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - "./frontend:/app"
      - /app/node_modules  # <-- Preserves container's node_modules
    networks:
      - reservation-api
    command: ["npm", "run", "dev"]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - reservation-api

volumes:
  mongo_data:

networks:
  reservation-api:
